### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by BigDeepBlue** [tspb/Async_API_sprint_2#2]
Добрый день! Есть несколько замечаний

1. [можно лучше] С развитием проекта в тестах фикстур будет все больше и больше, и их нужно систематизировать. Можно вынести в отдельный файл (затем добавлять другие файлы, логически разделяя их) и тем самым облегчим conftest.py. Для этого в conftest.py есть [pytest_plugins](https://docs.pytest.org/en/latest/how-to/fixtures.html#using-fixtures-from-other-projects)
2. [можно лучше] В скриптах ожидания ES и Redis в тестах (tests/functional/utils/) вместо вечного цикла, в который можно попасть при возникновении сложностей, лучше использовать backoff из прошлых спринтов. Он более функционален в сравнении с вечным циклом, теоретически он может сигнализировать команде поддержки после определенного количества попыток
3. [можно лучше]  https://github.com/tspb/Async_API_sprint_2/blob/2c9a284c227f72f7c219e7f622265de7444e70f1/tests/functional/src/test_film.py#L12 Маркер `pytest.mark.asyncio` можно указать один раз на уровне файла: https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.20.2/
4. https://github.com/tspb/Async_API_sprint_2/blob/2c9a284c227f72f7c219e7f622265de7444e70f1/FastAPI/src/services/common.py#L16
Здесь жестко привязались к `redis` и `ES`, но это не гибко, т.к технологии могут меняться. Лучше сделать абстрактный класс для движка, не зависящий от технологий

    Пример для движка
    
    Cначала определяем интерфейс через абстрактный класс:
    
    ```python
    class AsyncSearchEngine(ABC):
        @abstractmethod
        async def get_by_id(self, index: str, _id: str) -> Any | None:
            pass
    
        @abstractmethod
        async def def _get_by_ids(self, index: str, ids: list[str]) -> list[Any] | None:
            pass
    ```
    
    Затем можно наследоваться от этого класса и реализовать методы для конкретного поискового движка. Например для ElasticSearch.
    
    ```python
    class ElasticAsyncSearchEngine(AsyncSearchEngine):
        async def get_by_id(self, index: str, _id: str) -> Any | None:
             тут реализация метода для elastic
    
        async def get_by_ids(
               self, index: str, ids: list[str]
        ) -> list[Any] | None:
             тут реализация метода для elastic
    ``` 
    
    Потом использовать экземпляр ElasticAsyncSearchEngine в классе с бизнес логикой.
    
    ```python
    class BaseService(abc.ABC):
        def __init__(self, search_engine: AsyncSearchEngine):
            self.search_engine = search_engine
    
        async def get_by_id(self, obj_id: str) -> Optional[BaseServiceModelChild]:
            obj = await self.search_engine.get_by_id(obj_id)
            return obj
    ```        
            
    И далее наследовать уже конкретные сервисы
    
    ```python
    class FilmService(BaseService):
    ```
    
    Главная цель такого подхода, чтобы весь проект продолжил работать с новым движком без изменений в коде с бизнес логикой.
    
    Хороший пример [тут](https://qna.habr.com/q/744609)

**Comment by tspb** [comment]
Исправил 3, 4
